### ISSUE TITLE
How to not display certain fields?

### ISSUE THREAD

**Issue by thecodingaviator** [cengizhanbasak/react-date-countdown-timer#4]
Hi,

Is there any way I can leave out seconds, minutes and hours out and not have them rendered?

**Comment by thecodingaviator** [comment]
Rather, how can I make it days/minutes/hours?

**Comment by cengizhanbasak** [comment]
Hello, 

You can use the most significant figure and the number of figure fields.
In your case: mostSignificantFigure={'day'} numberOfFigures={3}

**Comment by thecodingaviator** [comment]
Thanks!
